FROM devbeta.d.jele.io/glassfish:7.0.3-correttojdk-17.0.6.10.1

LABEL name="GlassFish_AD"
LABEL nodeType="ad-glassfish"
LABEL nodeTypeAlias=""
LABEL lastCompatibleVersion="8.3.1"
LABEL cluster="https://raw.githubusercontent.com/annajel/glassfish/master/7.0.3-correttojdk-17.0.6.10.1/cluster.json" 
