FROM devbeta.d.jele.io/glassfish:7.0.5-zulujdk-17.0.7

LABEL name="GlassFishA"
LABEL nodeType="ad-glassfish"
LABEL nodeTypeAlias=""
LABEL lastCompatibleVersion="8.2.1"
LABEL cluster="https://raw.githubusercontent.com/ademianchuk/glassfish/master/7.0.5-zulujdk-17.0.7/cluster.json"
ENV ON_ENV_INSTALL=https://raw.githubusercontent.com/ademianchuk/glassfish-cluster/master/addons/auto-cluster.jps
